---
title: "練習1"
date: "2018-10-03"
output: html_document
params:
  studentID: "410478037"
  studentName: "彭思凱"
---

## 1
引入[五大銀行一個月定存固定利率歷史月資料](https://raw.githubusercontent.com/tpemartin/github-data/master/bankdata.csv)。

```{r}
library(readr)
bankdata <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/bankdata.csv")
```

### 1.1
將**銀行**變數改成factor
```{r ans11}
library(dplyr)
?as.factor
library(magrittr)
bankdata$銀行<-as.factor(bankdata$銀行)
```
```{r}
library(dplyr)
library(lubridate)
x<-c("099-01","099-02","099-03")
x
for (i in 1:3)
{
    x[i]=as.factor(x[i])
    a[i]=ymd(x[i])
}


```
### 1.2
將年月改成西元年月
```{r ans12}
library(dplyr)
library(stringr)
library(lubridate)
?str_c
str_c("1",bankdata$年月,"/01")->民國年月
ymd(民國年月)->民國年月
str_c(民國年月 + years(911))->西元年月

format(as.POSIXct(西元年月日),format="%Y/%m")->西元年月

西元年月
```


## 2
Google天災地圖會發佈天災時地資訊，如[潭美颱風(Typhoon Trami)](https://google.org/crisismap/google.com/2018-trami)，但它的時間是以UTC表示，如"2018/30/09 00:00 UTC",試透過`lubridate::with_tz()`將"2018/30/09 00:00 UTC"轉成台灣時間。(Hint: 台灣tzone可用`grep("Taipei",OlsonNames(),value=TRUE)`指令查得)

```{r}
grep("Taipei",OlsonNames(),value=TRUE)
??with_tz

```
```{r ans2}
?ymd_hm
library(dplyr)
library(stringr)
library(lubridate)
台灣時間 <- ymd_hm("2018/30/09 00:00 UTC", tzone = "Asia/Taipei")
with_tz(台灣時間, "GMT")
台灣時間
```

